// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf4FR_uMN4oTdpjx4NhObCSFch3KsSu4A',
    appId: '1:886452785737:web:e106f400e86001f14ae598',
    messagingSenderId: '886452785737',
    projectId: 'fir-auth-18280',
    authDomain: 'fir-auth-18280.firebaseapp.com',
    storageBucket: 'fir-auth-18280.appspot.com',
    measurementId: 'G-MXFG1PVCRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_dNjaxKENjosnRK7VMA0WeyROy7DCHUs',
    appId: '1:886452785737:android:e6474eb113d721794ae598',
    messagingSenderId: '886452785737',
    projectId: 'fir-auth-18280',
    storageBucket: 'fir-auth-18280.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdj3cHM4HOscJhlxCAtZfv3l1fB23aGG4',
    appId: '1:886452785737:ios:b000d731bc8476fd4ae598',
    messagingSenderId: '886452785737',
    projectId: 'fir-auth-18280',
    storageBucket: 'fir-auth-18280.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdj3cHM4HOscJhlxCAtZfv3l1fB23aGG4',
    appId: '1:886452785737:ios:38b32d7597ce1c234ae598',
    messagingSenderId: '886452785737',
    projectId: 'fir-auth-18280',
    storageBucket: 'fir-auth-18280.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
